//! Property-Based Tests for Node.js Event History Format Correctness Properties.
//!
//! This module contains property-based tests that verify the correctness properties
//! defined in the design document for the Rust Event History Format alignment.
//!
//! # Correctness Properties Tested
//!
//! 1. **Event ID Monotonicity** (Property 1): EventIds are strictly increasing starting from 1
//! 2. **Event Type Mapping Consistency** (Property 2): (Action, Type) → EventType mapping is correct
//! 3. **Timestamp Format Validity** (Property 3): All timestamps match ISO 8601 format
//! 4. **PascalCase Field Names** (Property 4): All serialized JSON keys are PascalCase
//! 5. **JSON Array Output Format** (Property 5): History output is flat JSON array without wrapper

#[cfg(test)]
mod tests {
    use proptest::prelude::*;
    use regex::Regex;
    use serde_json::Value;

    use crate::checkpoint_server::{
        ErrorWrapper, EventProcessor, ExecutionStartedDetails, ExecutionStartedDetailsWrapper,
        ExecutionSucceededDetails, ExecutionSucceededDetailsWrapper, InvocationCompletedDetails,
        InvocationCompletedDetailsWrapper, NodeJsEventDetails, NodeJsEventType, NodeJsHistoryEvent,
        PayloadWrapper, RetryDetails, StepSucceededDetails, StepSucceededDetailsWrapper,
    };
    use aws_durable_execution_sdk::operation::{
        Operation, OperationAction, OperationType, OperationUpdate,
    };
    use aws_durable_execution_sdk::ErrorObject;

    // ============================================================================
    // Proptest Strategies for Generating Test Data
    // ============================================================================

    /// Strategy for generating valid (Action, Type) combinations that produce events.
    /// Only includes combinations that are mapped in the EventProcessor.
    fn valid_action_type_strategy() -> impl Strategy<Value = (OperationAction, OperationType)> {
        prop_oneof![
            // Execution events
            Just((OperationAction::Start, OperationType::Execution)),
            Just((OperationAction::Succeed, OperationType::Execution)),
            Just((OperationAction::Fail, OperationType::Execution)),
            // Step events
            Just((OperationAction::Start, OperationType::Step)),
            Just((OperationAction::Succeed, OperationType::Step)),
            Just((OperationAction::Fail, OperationType::Step)),
            Just((OperationAction::Retry, OperationType::Step)),
            // Wait events
            Just((OperationAction::Start, OperationType::Wait)),
            Just((OperationAction::Succeed, OperationType::Wait)),
            // Callback events
            Just((OperationAction::Start, OperationType::Callback)),
            // Context events
            Just((OperationAction::Start, OperationType::Context)),
            Just((OperationAction::Succeed, OperationType::Context)),
            Just((OperationAction::Fail, OperationType::Context)),
        ]
    }

    /// Strategy for generating a sequence of valid (Action, Type) combinations.
    fn action_type_sequence_strategy(
        min_len: usize,
        max_len: usize,
    ) -> impl Strategy<Value = Vec<(OperationAction, OperationType)>> {
        prop::collection::vec(valid_action_type_strategy(), min_len..=max_len)
    }

    // ============================================================================
    // Property 1: Event ID Monotonicity
    // **Validates: Correctness Property 1, Requirement 1.2**
    //
    // For any sequence of events E₁, E₂, ..., Eₙ generated by the EventProcessor:
    // - E₁.EventId = 1
    // - ∀i ∈ [2, n]: Eᵢ.EventId = Eᵢ₋₁.EventId + 1
    // ============================================================================

    proptest! {
        /// Property test verifying that EventIds are strictly increasing starting from 1.
        ///
        /// **Validates: Correctness Property 1, Requirement 1.2**
        ///
        /// This test generates random sequences of operations and verifies that:
        /// 1. The first event has EventId = 1
        /// 2. Each subsequent event has EventId = previous EventId + 1
        #[test]
        fn prop_event_id_monotonicity(
            sequence in action_type_sequence_strategy(1, 50)
        ) {
            let mut processor = EventProcessor::new();
            let mut all_events: Vec<NodeJsHistoryEvent> = Vec::new();

            // Generate events for each (action, type) combination
            for (i, (action, op_type)) in sequence.iter().enumerate() {
                let op_id = format!("op-{}", i);
                let operation = Operation::new(&op_id, *op_type);
                let update = create_operation_update(&op_id, *action, *op_type);

                let events = processor.process_operation_update(&update, &operation);
                all_events.extend(events);
            }

            // Verify the property: EventIds are strictly increasing starting from 1
            if !all_events.is_empty() {
                // First event must have EventId = 1
                prop_assert_eq!(
                    all_events[0].event_id, 1,
                    "First event must have EventId = 1, got {}",
                    all_events[0].event_id
                );

                // Each subsequent event must have EventId = previous + 1
                for i in 1..all_events.len() {
                    prop_assert_eq!(
                        all_events[i].event_id,
                        all_events[i - 1].event_id + 1,
                        "Event {} has EventId {}, expected {} (previous was {})",
                        i,
                        all_events[i].event_id,
                        all_events[i - 1].event_id + 1,
                        all_events[i - 1].event_id
                    );
                }
            }
        }
    }

    /// Helper function to create an OperationUpdate for testing.
    fn create_operation_update(
        op_id: &str,
        action: OperationAction,
        op_type: OperationType,
    ) -> OperationUpdate {
        match action {
            OperationAction::Start => {
                if op_type == OperationType::Wait {
                    OperationUpdate::start_wait(op_id, 30)
                } else {
                    let mut update = OperationUpdate::start(op_id, op_type);
                    update.result = Some("{}".to_string());
                    update
                }
            }
            OperationAction::Succeed => {
                OperationUpdate::succeed(op_id, op_type, Some("{}".to_string()))
            }
            OperationAction::Fail => OperationUpdate::fail(
                op_id,
                op_type,
                ErrorObject::new("TestError", "Test error message"),
            ),
            OperationAction::Retry => OperationUpdate::retry(op_id, op_type, None, Some(5)),
            OperationAction::Cancel => OperationUpdate::cancel(op_id, op_type),
        }
    }

    // ============================================================================
    // Property 2: Event Type Mapping Consistency
    // **Validates: Correctness Property 2, Requirements 2.1-2.12**
    //
    // For any operation update with action A and type T, the generated event type
    // must match the expected mapping from the design specification.
    // ============================================================================

    /// Returns the expected NodeJsEventType for a given (Action, Type) combination.
    /// Returns None if the combination doesn't produce an event.
    fn expected_event_type(
        action: OperationAction,
        op_type: OperationType,
    ) -> Option<NodeJsEventType> {
        match (action, op_type) {
            // Execution events
            (OperationAction::Start, OperationType::Execution) => {
                Some(NodeJsEventType::ExecutionStarted)
            }
            (OperationAction::Succeed, OperationType::Execution) => {
                Some(NodeJsEventType::ExecutionSucceeded)
            }
            (OperationAction::Fail, OperationType::Execution) => {
                Some(NodeJsEventType::ExecutionFailed)
            }
            // Step events
            (OperationAction::Start, OperationType::Step) => Some(NodeJsEventType::StepStarted),
            (OperationAction::Succeed, OperationType::Step) => Some(NodeJsEventType::StepSucceeded),
            (OperationAction::Fail, OperationType::Step) => Some(NodeJsEventType::StepFailed),
            (OperationAction::Retry, OperationType::Step) => Some(NodeJsEventType::StepFailed),
            // Wait events
            (OperationAction::Start, OperationType::Wait) => Some(NodeJsEventType::WaitStarted),
            (OperationAction::Succeed, OperationType::Wait) => Some(NodeJsEventType::WaitSucceeded),
            // Callback events
            (OperationAction::Start, OperationType::Callback) => {
                Some(NodeJsEventType::CallbackStarted)
            }
            // Context events
            (OperationAction::Start, OperationType::Context) => {
                Some(NodeJsEventType::ContextStarted)
            }
            (OperationAction::Succeed, OperationType::Context) => {
                Some(NodeJsEventType::ContextSucceeded)
            }
            (OperationAction::Fail, OperationType::Context) => Some(NodeJsEventType::ContextFailed),
            // Other combinations don't produce events
            _ => None,
        }
    }

    proptest! {
        /// Property test verifying that (Action, Type) → EventType mapping is correct.
        ///
        /// **Validates: Correctness Property 2, Requirements 2.1-2.12**
        ///
        /// This test generates all valid (Action, Type) combinations and verifies
        /// that the correct EventType is produced according to the mapping table.
        #[test]
        fn prop_event_type_mapping_consistency(
            (action, op_type) in valid_action_type_strategy()
        ) {
            let mut processor = EventProcessor::new();
            let operation = Operation::new("test-op", op_type);
            let update = create_operation_update("test-op", action, op_type);

            let events = processor.process_operation_update(&update, &operation);

            // Get the expected event type
            let expected = expected_event_type(action, op_type);

            match expected {
                Some(expected_type) => {
                    // Should produce exactly one event with the expected type
                    prop_assert_eq!(
                        events.len(), 1,
                        "Expected 1 event for ({:?}, {:?}), got {}",
                        action, op_type, events.len()
                    );
                    prop_assert_eq!(
                        events[0].event_type, expected_type,
                        "For ({:?}, {:?}): expected {:?}, got {:?}",
                        action, op_type, expected_type, events[0].event_type
                    );
                }
                None => {
                    // Should not produce any events
                    prop_assert!(
                        events.is_empty(),
                        "Expected no events for ({:?}, {:?}), got {}",
                        action, op_type, events.len()
                    );
                }
            }
        }
    }

    /// Exhaustive test for all valid (Action, Type) → EventType mappings.
    /// This complements the property test by explicitly testing each mapping.
    #[test]
    fn test_all_event_type_mappings() {
        let mappings = vec![
            // Execution events
            (
                (OperationAction::Start, OperationType::Execution),
                NodeJsEventType::ExecutionStarted,
            ),
            (
                (OperationAction::Succeed, OperationType::Execution),
                NodeJsEventType::ExecutionSucceeded,
            ),
            (
                (OperationAction::Fail, OperationType::Execution),
                NodeJsEventType::ExecutionFailed,
            ),
            // Step events
            (
                (OperationAction::Start, OperationType::Step),
                NodeJsEventType::StepStarted,
            ),
            (
                (OperationAction::Succeed, OperationType::Step),
                NodeJsEventType::StepSucceeded,
            ),
            (
                (OperationAction::Fail, OperationType::Step),
                NodeJsEventType::StepFailed,
            ),
            (
                (OperationAction::Retry, OperationType::Step),
                NodeJsEventType::StepFailed,
            ),
            // Wait events
            (
                (OperationAction::Start, OperationType::Wait),
                NodeJsEventType::WaitStarted,
            ),
            (
                (OperationAction::Succeed, OperationType::Wait),
                NodeJsEventType::WaitSucceeded,
            ),
            // Callback events
            (
                (OperationAction::Start, OperationType::Callback),
                NodeJsEventType::CallbackStarted,
            ),
            // Context events
            (
                (OperationAction::Start, OperationType::Context),
                NodeJsEventType::ContextStarted,
            ),
            (
                (OperationAction::Succeed, OperationType::Context),
                NodeJsEventType::ContextSucceeded,
            ),
            (
                (OperationAction::Fail, OperationType::Context),
                NodeJsEventType::ContextFailed,
            ),
        ];

        for ((action, op_type), expected_type) in mappings {
            let mut processor = EventProcessor::new();
            let operation = Operation::new("test-op", op_type);
            let update = create_operation_update("test-op", action, op_type);

            let events = processor.process_operation_update(&update, &operation);

            assert_eq!(
                events.len(),
                1,
                "Expected 1 event for ({:?}, {:?}), got {}",
                action,
                op_type,
                events.len()
            );
            assert_eq!(
                events[0].event_type, expected_type,
                "For ({:?}, {:?}): expected {:?}, got {:?}",
                action, op_type, expected_type, events[0].event_type
            );
        }
    }

    // ============================================================================
    // Property 3: Timestamp Format Validity
    // **Validates: Correctness Property 3, Requirements 1.4, 4.3, 4.4, 5.5**
    //
    // For any event E:
    // - E.EventTimestamp matches ISO 8601 format: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$
    // ============================================================================

    /// Regex pattern for ISO 8601 timestamp with millisecond precision and Z suffix.
    const ISO_8601_PATTERN: &str = r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$";

    proptest! {
        /// Property test verifying that all timestamps match ISO 8601 format.
        ///
        /// **Validates: Correctness Property 3, Requirements 1.4, 4.3, 4.4, 5.5**
        ///
        /// This test generates events at various times and verifies all timestamps
        /// match the ISO 8601 pattern: YYYY-MM-DDTHH:MM:SS.mmmZ
        #[test]
        fn prop_timestamp_format_validity(
            sequence in action_type_sequence_strategy(1, 20)
        ) {
            let iso_regex = Regex::new(ISO_8601_PATTERN).unwrap();
            let mut processor = EventProcessor::new();

            for (i, (action, op_type)) in sequence.iter().enumerate() {
                let op_id = format!("op-{}", i);
                let operation = Operation::new(&op_id, *op_type);
                let update = create_operation_update(&op_id, *action, *op_type);

                let events = processor.process_operation_update(&update, &operation);

                for event in events {
                    prop_assert!(
                        iso_regex.is_match(&event.event_timestamp),
                        "Timestamp '{}' does not match ISO 8601 format ({})",
                        event.event_timestamp,
                        ISO_8601_PATTERN
                    );
                }
            }
        }
    }

    /// Test that the EventProcessor's timestamp formatting function produces valid ISO 8601.
    #[test]
    fn test_format_timestamp_iso8601() {
        use chrono::{TimeZone, Utc};

        let iso_regex = Regex::new(ISO_8601_PATTERN).unwrap();

        // Test various timestamps
        let test_cases = vec![
            Utc.with_ymd_and_hms(2025, 12, 3, 22, 58, 35).unwrap()
                + chrono::Duration::milliseconds(94),
            Utc.with_ymd_and_hms(2000, 1, 1, 0, 0, 0).unwrap(),
            Utc.with_ymd_and_hms(2099, 12, 31, 23, 59, 59).unwrap()
                + chrono::Duration::milliseconds(999),
        ];

        for timestamp in test_cases {
            let formatted = EventProcessor::format_timestamp(timestamp);
            assert!(
                iso_regex.is_match(&formatted),
                "Timestamp '{}' does not match ISO 8601 format",
                formatted
            );
        }
    }

    /// Test that current_timestamp produces valid ISO 8601.
    #[test]
    fn test_current_timestamp_format() {
        let iso_regex = Regex::new(ISO_8601_PATTERN).unwrap();

        // Generate multiple timestamps to ensure consistency
        for _ in 0..10 {
            let timestamp = EventProcessor::current_timestamp();
            assert!(
                iso_regex.is_match(&timestamp),
                "Current timestamp '{}' does not match ISO 8601 format",
                timestamp
            );
        }
    }

    // ============================================================================
    // Property 4: PascalCase Field Names
    // **Validates: Correctness Property 4, Requirements 1.1, 5.4**
    //
    // For any serialized event JSON:
    // - All top-level field names match PascalCase pattern: ^[A-Z][a-zA-Z0-9]*$
    // - All nested field names match PascalCase pattern
    // ============================================================================

    /// Regex pattern for PascalCase field names.
    const PASCAL_CASE_PATTERN: &str = r"^[A-Z][a-zA-Z0-9]*$";

    /// Recursively check that all keys in a JSON value are PascalCase.
    fn verify_pascal_case_keys(
        value: &Value,
        path: &str,
        pascal_regex: &Regex,
    ) -> Result<(), String> {
        match value {
            Value::Object(map) => {
                for (key, val) in map {
                    if !pascal_regex.is_match(key) {
                        return Err(format!(
                            "Key '{}' at path '{}' is not PascalCase (pattern: {})",
                            key, path, PASCAL_CASE_PATTERN
                        ));
                    }
                    let new_path = if path.is_empty() {
                        key.clone()
                    } else {
                        format!("{}.{}", path, key)
                    };
                    verify_pascal_case_keys(val, &new_path, pascal_regex)?;
                }
            }
            Value::Array(arr) => {
                for (i, val) in arr.iter().enumerate() {
                    let new_path = format!("{}[{}]", path, i);
                    verify_pascal_case_keys(val, &new_path, pascal_regex)?;
                }
            }
            _ => {}
        }
        Ok(())
    }

    proptest! {
        /// Property test verifying that all serialized JSON keys are PascalCase.
        ///
        /// **Validates: Correctness Property 4, Requirements 1.1, 5.4**
        ///
        /// This test serializes various events to JSON and verifies all keys
        /// match the PascalCase pattern.
        #[test]
        fn prop_pascal_case_field_names(
            (action, op_type) in valid_action_type_strategy()
        ) {
            let pascal_regex = Regex::new(PASCAL_CASE_PATTERN).unwrap();
            let mut processor = EventProcessor::new();
            let operation = Operation::new("test-op", op_type);
            let update = create_operation_update("test-op", action, op_type);

            let events = processor.process_operation_update(&update, &operation);

            for event in events {
                let json_str = serde_json::to_string(&event)
                    .expect("Failed to serialize event to JSON");
                let json_value: Value = serde_json::from_str(&json_str)
                    .expect("Failed to parse JSON");

                if let Err(e) = verify_pascal_case_keys(&json_value, "", &pascal_regex) {
                    prop_assert!(false, "PascalCase violation: {}", e);
                }
            }
        }
    }

    /// Test PascalCase for all event types with their specific details.
    #[test]
    fn test_pascal_case_all_event_types() {
        let pascal_regex = Regex::new(PASCAL_CASE_PATTERN).unwrap();

        // Create events with various detail types
        let events = vec![
            create_test_event(
                NodeJsEventType::ExecutionStarted,
                NodeJsEventDetails::ExecutionStarted(ExecutionStartedDetailsWrapper {
                    execution_started_details: ExecutionStartedDetails {
                        input: PayloadWrapper::new("{}"),
                        execution_timeout: Some(300),
                    },
                }),
            ),
            create_test_event(
                NodeJsEventType::ExecutionSucceeded,
                NodeJsEventDetails::ExecutionSucceeded(ExecutionSucceededDetailsWrapper {
                    execution_succeeded_details: ExecutionSucceededDetails {
                        result: PayloadWrapper::new("{}"),
                    },
                }),
            ),
            create_test_event(
                NodeJsEventType::StepSucceeded,
                NodeJsEventDetails::StepSucceeded(StepSucceededDetailsWrapper {
                    step_succeeded_details: StepSucceededDetails {
                        result: PayloadWrapper::new("{}"),
                        retry_details: RetryDetails::new(1),
                    },
                }),
            ),
            create_test_event(
                NodeJsEventType::InvocationCompleted,
                NodeJsEventDetails::InvocationCompleted(InvocationCompletedDetailsWrapper {
                    invocation_completed_details: InvocationCompletedDetails {
                        start_timestamp: "2025-12-03T22:58:35.094Z".to_string(),
                        end_timestamp: "2025-12-03T22:58:36.094Z".to_string(),
                        request_id: "req-123".to_string(),
                        error: ErrorWrapper::empty(),
                    },
                }),
            ),
        ];

        for event in events {
            let json_str = serde_json::to_string(&event).expect("Failed to serialize");
            let json_value: Value = serde_json::from_str(&json_str).expect("Failed to parse");

            if let Err(e) = verify_pascal_case_keys(&json_value, "", &pascal_regex) {
                panic!("PascalCase violation for {:?}: {}", event.event_type, e);
            }
        }
    }

    /// Helper function to create a test event with specific details.
    fn create_test_event(
        event_type: NodeJsEventType,
        details: NodeJsEventDetails,
    ) -> NodeJsHistoryEvent {
        NodeJsHistoryEvent {
            event_type,
            event_id: 1,
            id: Some("test-id".to_string()),
            event_timestamp: "2025-12-03T22:58:35.094Z".to_string(),
            sub_type: Some("Step".to_string()),
            name: Some("test-name".to_string()),
            parent_id: Some("parent-id".to_string()),
            details,
        }
    }

    // ============================================================================
    // Property 5: JSON Array Output Format
    // **Validates: Correctness Property 5, Requirements 5.1, 5.2, 5.3**
    //
    // For any serialized history H:
    // - H is a valid JSON array at root level (starts with `[`, ends with `]`)
    // - H does not contain an "events" wrapper key
    // - Events are ordered by EventId (strictly increasing)
    // ============================================================================

    proptest! {
        /// Property test verifying that history output is a flat JSON array without wrapper.
        ///
        /// **Validates: Correctness Property 5, Requirements 5.1, 5.2, 5.3**
        ///
        /// This test generates histories and verifies:
        /// 1. Output is a valid JSON array at root level
        /// 2. No "events" wrapper key exists
        /// 3. Events are ordered by EventId
        #[test]
        fn prop_json_array_output_format(
            sequence in action_type_sequence_strategy(1, 30)
        ) {
            let mut processor = EventProcessor::new();
            let mut all_events: Vec<NodeJsHistoryEvent> = Vec::new();

            // Generate events
            for (i, (action, op_type)) in sequence.iter().enumerate() {
                let op_id = format!("op-{}", i);
                let operation = Operation::new(&op_id, *op_type);
                let update = create_operation_update(&op_id, *action, *op_type);

                let events = processor.process_operation_update(&update, &operation);
                all_events.extend(events);
            }

            // Serialize as a flat JSON array (NodeJsHistoryFile format)
            let json_str = serde_json::to_string(&all_events)
                .expect("Failed to serialize history to JSON");

            // Property 1: Must be a valid JSON array at root level
            prop_assert!(
                json_str.starts_with('[') && json_str.ends_with(']'),
                "History JSON must start with '[' and end with ']', got: {}...{}",
                &json_str[..json_str.len().min(20)],
                &json_str[json_str.len().saturating_sub(20)..]
            );

            // Property 2: Must not contain "events" wrapper key
            let json_value: Value = serde_json::from_str(&json_str)
                .expect("Failed to parse JSON");

            prop_assert!(
                json_value.is_array(),
                "Root JSON value must be an array, got: {:?}",
                json_value
            );

            // Check that there's no "events" key anywhere at the root level
            if let Value::Object(map) = &json_value {
                prop_assert!(
                    !map.contains_key("events"),
                    "History JSON must not contain 'events' wrapper key"
                );
            }

            // Property 3: Events must be ordered by EventId (strictly increasing)
            if let Value::Array(arr) = &json_value {
                let mut prev_event_id: Option<u64> = None;
                for (i, event_value) in arr.iter().enumerate() {
                    if let Some(event_id) = event_value.get("EventId").and_then(|v| v.as_u64()) {
                        if let Some(prev_id) = prev_event_id {
                            prop_assert!(
                                event_id > prev_id,
                                "Events must be ordered by EventId. Event {} has EventId {}, but previous was {}",
                                i, event_id, prev_id
                            );
                        }
                        prev_event_id = Some(event_id);
                    }
                }
            }
        }
    }

    /// Test that an empty history serializes to an empty JSON array.
    #[test]
    fn test_empty_history_is_empty_array() {
        let events: Vec<NodeJsHistoryEvent> = Vec::new();
        let json_str = serde_json::to_string(&events).expect("Failed to serialize");

        assert_eq!(json_str, "[]", "Empty history must serialize to '[]'");
    }

    /// Test that a single event history is a valid JSON array.
    #[test]
    fn test_single_event_history_is_array() {
        let event = create_test_event(
            NodeJsEventType::ExecutionStarted,
            NodeJsEventDetails::ExecutionStarted(ExecutionStartedDetailsWrapper {
                execution_started_details: ExecutionStartedDetails {
                    input: PayloadWrapper::new("{}"),
                    execution_timeout: None,
                },
            }),
        );

        let events = vec![event];
        let json_str = serde_json::to_string(&events).expect("Failed to serialize");

        assert!(json_str.starts_with('['), "History must start with '['");
        assert!(json_str.ends_with(']'), "History must end with ']'");

        let json_value: Value = serde_json::from_str(&json_str).expect("Failed to parse");
        assert!(json_value.is_array(), "Root must be an array");
    }

    /// Test that history does not use an "events" wrapper.
    #[test]
    fn test_no_events_wrapper() {
        let mut processor = EventProcessor::new();
        let operation = Operation::new("exec-1", OperationType::Execution);
        let update =
            create_operation_update("exec-1", OperationAction::Start, OperationType::Execution);

        let events = processor.process_operation_update(&update, &operation);
        let json_str = serde_json::to_string(&events).expect("Failed to serialize");

        // Should NOT contain "events" as a key
        assert!(
            !json_str.contains(r#""events""#),
            "History JSON should not contain 'events' wrapper key"
        );

        // Should be a direct array
        let json_value: Value = serde_json::from_str(&json_str).expect("Failed to parse");
        assert!(
            json_value.is_array(),
            "History should be a direct array, not wrapped in an object"
        );
    }
}
